apps/login/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login_reg$', views.login_reg, name='login_reg'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^success$', views.success, name='success'),
]

apps/secrets/urls.py
from django.conf.urls import url
from . import views           

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^secret$', views.secret, name='secret'),
    url(r'^destroy/(?P<id>\d+)$', views.destroy, name='destroy'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^like/(?P<id>\d+)$', views.like, name='like'),
    url(r'^hotsecrets$', views.hotsecrets, name='hotsecrets'),
  ]

doj_secrets/urls.py
from django.conf.urls import url, include


urlpatterns = [ 
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^secrets/', include('apps.secrets.urls', namespace='secrets'))
]

apps/login/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
import bcrypt, re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def validate_reg(self, request):
        errors = self.validate_inputs(request)

        if errors:
            return (False, errors)

        pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())

        user = self.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], password=pw_hash)

        return (True, user)

    def validate_login(self, request):
        try:
            user = User.objects.get(email=request.POST['email'])
            password = request.POST['password'].encode()
            if bcrypt.hashpw(password, user.password.encode()):
                return (True, user)

        except ObjectDoesNotExist:
            pass

        return (False, ["Invalid login."])

    def validate_inputs(self, request):
        errors = []

        if not request.POST['first_name']:
            errors.append('First name cannot be blank.')
        if not EMAIL_REGEX.match(request.POST['email']):
            errors.append('Invalid email.')
        if request.POST['password'] < 8:
            errors.append('Password must be at least 8 characters.')
        if request.POST['password'] != request.POST['confirm']:
            errors.append('Password and password confirm must match.')

        return errors

class User(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    email = models.CharField(max_length = 50)
    password = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/secrets/models.py
from __future__ import unicode_literals
from ..login.models import User
from django.db import models

class SecretManager(models.Manager):
    def post_secret(self, request):
        errors = []

        if not request.POST['new_secret']:
            errors.append('Please write a secret!')

        else:
            creator = User.objects.get(id=request.session['user']['user_id'])
            self.create(content=request.POST['new_secret'], secret_creator=creator)

        return errors

    def destroy_secret(self, request, id):
        putitin = Secret.objects.filter(id=id).delete()

    def like_secret(self,request, id):
        user = User.objects.get(id=request.session['user']['user_id'])
        secret = Secret.objects.get(id=id)
        secret.likes.add(user)

class Secret(models.Model):
    content = models.CharField(max_length=325)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    secret_creator = models.ForeignKey(User, related_name = 'user_secret')
    likes = models.ManyToManyField(User, related_name = 'user_likes')
    objects = SecretManager()

apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from models import User

def session_check(request):
    if 'user' in request.session:
        return True
    else:
        return False

def index(request):
    if session_check(request):
        # VV REDIRECT TO APP VV
        return redirect('secrets:index')
    else:
        return render(request,'login/index.html')

def login_reg(request):
    if request.POST['action'] == 'register':
        result = User.objects.validate_reg(request)

    elif request.POST['action'] == 'login':
        result = User.objects.validate_login(request)

    if result[0] == False:
        print_errors(request, result[1])
        return redirect('login:index')

    return log_user_in(request, result[1])

def print_errors(request, error_list):
    for error in error_list:
        messages.add_message(request, messages.INFO, error)

def log_user_in(request, user):
    request.session['user'] = {
        'user_id': user.id,
        'first_name': user.first_name
    }

    # VV REDIRECT TO APP VV
    return redirect('secrets:index')

def logout(request):
    request.session.clear()

    return redirect('login:index')

def success(request):
    return render(request, 'login/success.html')

apps/secrets/views.py
from django.shortcuts import render, HttpResponse, redirect
from models import User, Secret
from django.contrib import messages
from django.db.models import Count
# from models whatever our tables are
  # Create your views here.

def session_check(request):
  if 'user' in request.session:
      return True
  else:
      return False

def print_errors(request, error_list):
    for error in error_list:
        messages.add_message(request, messages.INFO, error)

def secret(request):
    if not session_check(request):
        return redirect('secrets:index')

    result = Secret.objects.post_secret(request)

    if result:
        print_errors(request, result)

    return redirect('secrets:index')


def destroy(request, id):
    if not session_check(request):
        return redirect('secrets:index')
    else:
        Secret.objects.destroy_secret(request, id)

        return redirect('secrets:index')
def like(request, id):
    Secret.objects.like_secret(request, id)
    return redirect('secrets:index')

def index(request):
    if not session_check(request):
        return redirect('secrets:index')

    context = {
        'secrets': Secret.objects.order_by('-created_at')[:10],
        'logged_in_user': User.objects.get(id=request.session['user']['user_id']),
    }

    return render(request, 'secrets/index.html', context)

def hotsecrets(request):
    if not session_check(request):
        return redirect('secrets:index')

    context = {
        'secrets': Secret.objects.annotate(num_HOT=Count('likes')).order_by('-num_HOT'),
        'logged_in_user': User.objects.get(id=request.session['user']['user_id']),
    }

    return render(request, 'secrets/hotsecrets.html', context)
def logout(request):
    request.session.clear()

    return redirect('login:index')

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Login</title>
    {% load static %}
</head>

<body>
    <div id="wrapper">
        <h2>Log In</h2>
        <form action="{% url 'login:login_reg' %}" method="post">
            {% csrf_token %}
            <p>Email: <input type="text" name="email"></p>
            <p>Password: <input type="password" name="password"></p>
            <input type="hidden" name="action" value="login">
            <input type="submit" name="submit" value="submit">
        </form><!-- Login -->
        <h2>Register</h2>
        <form action="{% url 'login:login_reg' %}" method="post">
            {% csrf_token %}
            <p>First Name: <input type="text" name="first_name"></p>
            <p>Last Name: <input type="text" name="last_name"></p>
            <p>Email: <input type="text" name="email"></p>
            <p>Password: <input type="password" name="password"></p>
            <p>Confirm Password: <input type="password" name="confirm"></p>
            <input type="hidden" name="action" value="register">
            <input type="submit" name="submit" value="submit">
        </form><!-- Registration -->
        {% if messages %}
            {% for message in messages %}
                <h5>{{ message }}</h5>
            {% endfor %}
       {% endif %}
    </div><!--  /#wrapper -->
</body>

</html>

apps/secrets/templates/secrets/hotsecrets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hot Secrets</title>
</head>
<body>
    <h1>Top all most hottest secrets</h1>
    <a href="{% url 'secrets:index' %}"><button>Back</button></a>
    {% for secret in secrets %}
    <div class="secret">
        <h5>{{ secret.created_at }}</h5>
        <p class="secret_content">{{ secret.content }}</p>
        <p>{{ secret.likes.count }}</p>
        {% if logged_in_user not in secret.likes.all %}
        <a href="{% url 'secrets:like' secret.id %}" class="like_secret"><button class="like_button">Like</button></a>
        {% endif %}
        {% if secret.secret_creator.id == request.session.user.user_id %}
            <p>You posted this.</p>
            <a href="{% url 'secrets:destroy' secret.id %}" class="delete_secret"><button class="delete_button">Delete Secret</button></a>
        {% endif %}
    {% endfor %}
    </div><!--  /.secret -->
    {% if not secrets %}
        <p class="nothing">No secrets here...</p>
    {% endif %}
</body>
</html>

apps/secrets/templates/secrets/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Shhhhh...</title>
</head>

<body>
    <h1>DojSecrets</h1>
    <h2>Ab frpergf urer... ;)</h2>
    <a href="{% url 'secrets:logout' %}"><button>Logout</button></a>
    <a href="{% url 'secrets:hotsecrets' %}"><button>HOT Secrets</button></a>
    <form action="{% url 'secrets:secret' %}" method="POST">
            {% csrf_token %}
        <p><textarea name="new_secret" class="secret_field" rows="8" cols="40"></textarea></p>
        <p><input type="submit" value="Secret" class="secret_submit"></p>
    </form>
        {% if messages %}
            {% for message in messages %}
                <h5>{{ message }}</h5>
            {% endfor %}
        {% endif %}
        {% for secret in secrets %}
        <div class="secret">
            <h5>{{ secret.created_at }}</h5>
            <p class="secret_content">{{ secret.content }}</p>
            <p>Likes: {{ secret.likes.count }}</p>
            {% if logged_in_user not in secret.likes.all %}
            <a href="{% url 'secrets:like' secret.id %}" class="like_secret"><button class="like_button">Like</button></a>
            {% else %}
            <p>You liked this.</p>
            {% endif %}
            {% if secret.secret_creator.id == request.session.user.user_id %}
                <p>You posted this.</p>
                <a href="{% url 'secrets:destroy' secret.id %}" class="delete_secret"><button class="delete_button">Delete Secret</button></a>
            {% endif %}
        {% endfor %}
        </div><!--  /.secret -->
        {% if not secrets %}
            <p class="nothing">No secrets here...</p>
        {% endif %}
</body>

</html>